name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 10 * * *"   # Monday at 10:00 UT   # Thursday at 10:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase storage file
        run: |
          curl -I https://gdvhrnkvqmlbbtoulubc.supabase.co/storage/v1/object/public/quran/100.png
